config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 30 }
  validates :content, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end


  def create
    @post = Post.new(params.require(:post).permit(:title, :content))
    if @post.save
      flash[:notice] = "Post was created successfully."
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params.require(:post).permit(:title, :content))
      flash[:notice] = "Post was updated successfully."
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareIt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag asset_path('favicon-32x32.png') %>
    <style>
    table,
    th,
    td {
      padding: 10px;
      border: 1px solid black;
      border-collapse: collapse;
    }
  </style>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>  
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<p>
This website has been created with minimalism in mind, that's why we employ near to zero CSS and try to make website as barebone as possible, while still doing the job.
</p>
<p>
Idea is simple, share the post, write anything you want in it, and browse other posts. Everyone can contribute.

</p>

<p>
There are only few restrictions: Title of the post has to be between 6 and 30 characters and content has to be between 10 and 1000.
</p>

<%= link_to 'Posts listing', posts_path %> |
<%= link_to 'Home page', root_path %> 

app/views/pages/home.html.erb
<h1>Welcome to ShareIt!</h1>

<p>You can read about this website in the about section, or jump straight into posts.</p>

<%= link_to 'Posts listing', posts_path %> |
<%= link_to 'About page', about_path %> 

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<% if @post.errors.any? %>
  <h2>The following errors prevented the post from being saved</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @post, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br/>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Cancel and return to posts listing', posts_path %> 

app/views/posts/index.html.erb
<h1>Here are all of the posts available:</h1>

<table>
  <thead>
    <tr>
      <th>Time created</th>
      <th>Title</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.created_at %></td>
        <td><%= post.title %></td>
        <td><%= link_to 'Show post', post_path(post) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Create new post', new_post_path %> |
  <%= link_to 'Home page', root_path %> 
</p>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

<% if @post.errors.any? %>
  <h2>The following errors prevented the post from being saved:</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with scope: :post, url: posts_path, local: true do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title, size: "30" %>
  </p>

  <p>
    <%= f.label :content %><br/>
    <%= f.text_area :content, rows: "10", cols: "30" %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Return to posts listing', posts_path %> 

app/views/posts/show.html.erb
<h1>Here is the post:</h1>

<p><strong>Title: </strong><%= @post.title %></p>
<p><strong>Content: </strong><%= @post.content %></p>

<%= link_to 'Return to posts listing', posts_path %> 